module Configuration
  TITLE = 'Tetris'
  BOARD_WIDTH = 20
  BOARD_HEIGHT = 25
  SCREEN_WIDTH = BOARD_WIDTH + 2
  SCREEN_HEIGHT = BOARD_HEIGHT + 2
  RENDER_CHARACTER = 'O'
  INITIAL_SPEED = 0.4
  SPEED_INCREMENT = 1.05
  SPEEDUP_FACTOR = 1.5
end