module Configuration
  TITLE = 'Tetris'
  BOARD_WIDTH = 20
  BOARD_HEIGHT = 25
  SCREEN_PADDING_TOP = 3
  SCREEN_PADDING_LEFT = 1
  SCREEN_WIDTH = BOARD_WIDTH + SCREEN_PADDING_LEFT + 1
  SCREEN_HEIGHT = BOARD_HEIGHT + SCREEN_PADDING_TOP + 1
  # RENDER_CHARACTER = 'o'
  RENDER_CHARACTER = 'o'
  BOX_VERTICAL = '|'
  BOX_HORIZONTAL = '-'
  INITIAL_SPEED = 0.4
  SPEED_INCREMENT = 1.05
  SPEEDUP_FACTOR = 1.5
end