module Configuration
  TITLE = 'Tetris'
  BOARD_WIDTH = 20
  BOARD_HEIGHT = 20
  SCREEN_PADDING_TOP = 4
  SCREEN_PADDING_LEFT = 1
  SCREEN_WIDTH = BOARD_WIDTH + SCREEN_PADDING_LEFT + 1
  SCREEN_HEIGHT = BOARD_HEIGHT + SCREEN_PADDING_TOP + 1
  # RENDER_CHARACTER = 'o'
  RENDER_CHARACTER = 'o'
  BOX_VERTICAL = '|'
  BOX_HORIZONTAL = '-'
  FIRST_LEVEL_UP_SCORE = 5 # Score needed to reach level 2
  SCORE_NEXT_LEVEL_FACTOR = 1.5 # Score for level n = FIRST_LEVEL_UP_SCORE * SCORE_NEXT_LEVEL_FACTOR^(n-2), n >= 2
  INITIAL_SPEED = 0.4 # shape fall every 0.4 seconds
  FALLING_SPEED_FACTOR = 0.95 # 5% faster every level
  SPEEDUP_FACTOR = 1.5 # 50% faster when speedup
end